### ISSUE TITLE
Implement IsConstMethod

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/InterOp#13]
In the unittests we have a test checking if a method is const. We should provide the relevant implementation for it.

https://github.com/compiler-research/InterOp/blob/a16dedef4d8fa7d5833b179954c073726016d4bf/unittests/InterOp/FunctionReflectionTest.cpp#L607-L621

**Comment by utkarshraj779** [comment]
std::vector<Decl*> Decls, SubDecls;
  std::string code = R"(
    class C {
      void f1() const {}
      const void f1() {}
      void f2() {}
    };
    )";

**Comment by utkarshraj779** [comment]
@vgvassilev  now i merge it in fork i think it gonna work

**Comment by vgvassilev** [comment]
You will need to open a proper pull request and follow the general workflow that we have.

**Comment by Smit1603** [comment]
- @vgvassilev and @sudo-panda can I work on this issue???

**Comment by vgvassilev** [comment]
Sure, go for it.
