### ISSUE TITLE
Implement GetFunctionArgName

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/InterOp#14]
In the unittests we have a test returning the name of a function argument. We should provide the relevant implementation for it.

https://github.com/compiler-research/InterOp/blob/a16dedef4d8fa7d5833b179954c073726016d4bf/unittests/InterOp/FunctionReflectionTest.cpp#L623-L639

**Comment by utkarshraj779** [comment]
i was completed the this one alse in my pull request but did not show

**Comment by vgvassilev** [comment]
> i was completed the this one also in my pull request but did not show

Please take only one issue, solve it, submit a pull request with a good description and commit message and then move to the other. So far we have not seen any of these elements completed.

**Comment by utkarshraj779** [comment]
i am not familiar with git hub too much that why i did this mistake sorry

**Comment by Smit1603** [comment]
- @vgvassilev can I work on this issue???

**Comment by vgvassilev** [comment]
Go ahead.
