### ISSUE TITLE
Implement IsSubType Interface

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/InterOp#18]
https://github.com/compiler-research/InterOp/blob/a16dedef4d8fa7d5833b179954c073726016d4bf/unittests/InterOp/TypeReflectionTest.cpp#L330-L352

**Comment by utkarshraj779** [comment]
@vgvassilev can i solve this isue

**Comment by vgvassilev** [comment]
> @vgvassilev can i solve this isue

We have a pull request already that is pretty close to solve it.

**Comment by utkarshraj779** [comment]
so @vgvassilev can you suggest somewhere where I find more issues and solve them?

**Comment by vgvassilev** [comment]
This was implemented in PR #32
